# Generated by Django 6.1.1 on 2026-09-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mcq', 'Вопрос с вариантами'), ('open', 'Открытый вопрос'), ('case', 'Кейс с возражением')], max_length=10, verbose_name='Тип')),
                ('prompt', models.TextField(verbose_name='Текст вопроса / фраза клиента')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Элемент финального теста',
                'verbose_name_plural': 'Элементы финального теста',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finaltest.finaltestitem')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='FinalTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mcq_score_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Попытка финального теста',
                'verbose_name_plural': 'Попытки финального теста',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Письменный ответ')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='AI-оценка (заготовка на будущее)')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий админа')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltest.finaltestitem')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltest.finaltestoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='finaltest.finaltestsubmission')),
            ],
            options={
                'verbose_name': 'Ответ в финальном тесте',
                'verbose_name_plural': 'Ответы в финальном тесте',
            },
        ),
    ]
