# Generated by Django 6.1.1 on 2026-09-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitation_created_at_and_more'),
        ('finaltest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltestanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Верно'),
        ),
        migrations.AlterField(
            model_name='finaltestanswer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finaltest.finaltestitem', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='finaltestanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finaltest.finaltestoption', verbose_name='Выбранный вариант'),
        ),
        migrations.AlterField(
            model_name='finaltestanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='finaltest.finaltestsubmission', verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='finaltestsubmission',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(verbose_name='Попытка №'),
        ),
        migrations.AlterField(
            model_name='finaltestsubmission',
            name='mcq_score_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вопросы с вариантами, %'),
        ),
        migrations.AlterField(
            model_name='finaltestsubmission',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начата'),
        ),
        migrations.AlterField(
            model_name='finaltestsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_submissions', to='accounts.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='finaltestsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлена'),
        ),
    ]
