# Generated by Django 6.1.1 on 2026-09-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltest', '0002_alter_finaltestanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltestitem',
            name='prompt_uz',
            field=models.TextField(blank=True, verbose_name='Текст вопроса (узб.)'),
        ),
        migrations.AddField(
            model_name='finaltestoption',
            name='text_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Вариант ответа (узб.)'),
        ),
    ]
