# Generated by Django 6.1.1 on 2026-09-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltest', '0003_finaltestitem_prompt_uz_finaltestoption_text_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltestsubmission',
            name='draft',
            field=models.JSONField(blank=True, default=dict, verbose_name='Черновик ответов {id вопроса: ответ}'),
        ),
        migrations.AddField(
            model_name='finaltestsubmission',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Черновик сохранён'),
        ),
    ]
