# Generated by Django 6.1.1 on 2026-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltest', '0004_finaltestsubmission_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltestitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
