# Generated by Django 6.1.1 on 2026-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltest', '0005_alter_finaltestitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltestsubmission',
            name='item_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Вопросы этой попытки (в порядке показа)'),
        ),
    ]
