# Generated by Django 6.1.1 on 2026-09-25 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя ученика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает регистрации'), ('used', 'Использовано'), ('revoked', 'Отозвано')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Проходит обучение'), ('pending_review', 'На проверке'), ('approved', 'Допущен'), ('needs_rework', 'На доработку'), ('rejected', 'Отказ')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка админа')),
                ('final_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('invitation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='accounts.invitation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-started_at'],
            },
        ),
    ]
