# Generated by Django 6.1.1 on 2026-09-25 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает регистрации'), ('used', 'Использовано'), ('revoked', 'Отозвано')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использовано'),
        ),
        migrations.AlterField(
            model_name='student',
            name='invitation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='accounts.invitation', verbose_name='Приглашение'),
        ),
        migrations.AlterField(
            model_name='student',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Проходит обучение'), ('pending_review', 'На проверке'), ('approved', 'Допущен'), ('needs_rework', 'На доработку'), ('rejected', 'Отказ')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
