# Generated by Django 6.1.1 on 2026-09-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_invitation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cases', 'Кейсы: бизнес → решение'), ('odd', 'Нестандартные бизнесы'), ('route', 'Куда идти?'), ('tariff', 'Тарифы и продукты'), ('myth', 'Правда или миф'), ('money', 'Деньги и цифры')], max_length=10, verbose_name='Игра')),
                ('prompt', models.TextField(verbose_name='Вопрос / ситуация')),
                ('prompt_uz', models.TextField(blank=True, verbose_name='Вопрос (узб.)')),
                ('explanation', models.TextField(blank=True, verbose_name='Разбор (показывается после ответа)')),
                ('explanation_uz', models.TextField(blank=True, verbose_name='Разбор (узб.)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать стажёрам')),
            ],
            options={
                'verbose_name': 'Вопрос тренировки',
                'verbose_name_plural': 'Вопросы тренировки',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('text_uz', models.CharField(blank=True, max_length=300, verbose_name='Вариант ответа (узб.)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='practice.practicequestion')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='accounts.student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practicequestion')),
            ],
            options={
                'verbose_name': 'Ответ в тренировке',
                'verbose_name_plural': 'Ответы в тренировке',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
