# Generated by Django 6.1.1 on 2026-09-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок')),
                ('youtube_id', models.CharField(blank=True, help_text='ID видео из ссылки youtube.com/watch?v=XXXX', max_length=32, verbose_name='YouTube ID (unlisted)')),
                ('text_content', models.TextField(blank=True, verbose_name='Конспект (markdown)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='ModuleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('is_passed', models.BooleanField(default=False)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='onboarding.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Попытка прохождения модуля',
                'verbose_name_plural': 'Попытки прохождения модулей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onboarding.module')),
            ],
            options={
                'verbose_name': 'Контрольный вопрос',
                'verbose_name_plural': 'Контрольные вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.moduleattempt')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.moduleansweroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.modulequestion')),
            ],
            options={
                'verbose_name': 'Ответ в попытке',
                'verbose_name_plural': 'Ответы в попытках',
            },
        ),
        migrations.AddField(
            model_name='moduleansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='onboarding.modulequestion'),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='onboarding.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Прогресс по модулю',
                'verbose_name_plural': 'Прогресс по модулям',
                'unique_together': {('student', 'module')},
            },
        ),
    ]
