# Generated by Django 6.1.1 on 2026-09-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitation_created_at_and_more'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattempt',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(verbose_name='Попытка №'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='correct_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Верных ответов'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Пройдена'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='onboarding.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attempts', to='accounts.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='moduleattempt',
            name='total_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='onboarding.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='accounts.student', verbose_name='Ученик'),
        ),
    ]
