# Generated by Django 6.1.1 on 2026-09-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_moduleattempt_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='text_content_uz',
            field=models.TextField(blank=True, verbose_name='Конспект (узб., markdown)'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (узб.)'),
        ),
        migrations.AddField(
            model_name='module',
            name='youtube_id_uz',
            field=models.CharField(blank=True, help_text='Если пусто — будет показано русское видео', max_length=32, verbose_name='YouTube ID (узб.)'),
        ),
        migrations.AddField(
            model_name='moduleansweroption',
            name='text_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Вариант ответа (узб.)'),
        ),
        migrations.AddField(
            model_name='modulequestion',
            name='text_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='Вопрос (узб.)'),
        ),
    ]
