# Generated by Django 6.1.1 on 2026-09-26 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitation_created_at_and_more'),
        ('onboarding', '0003_module_text_content_uz_module_title_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='Выбранные ответы {id вопроса: id варианта}')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='onboarding.module', verbose_name='Модуль')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_drafts', to='accounts.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Черновик ответов на модуль',
                'verbose_name_plural': 'Черновики ответов на модули',
                'unique_together': {('student', 'module')},
            },
        ),
    ]
