# Generated by Django 6.1.1 on 2026-09-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_invitation_created_at_and_more'),
        ('onboarding', '0004_moduledraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('video', 'Видео'), ('text', 'Материал (текст)'), ('action', 'Практическое задание'), ('resource', 'Ссылка / файл')], default='text', max_length=10, verbose_name='Тип шага')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, help_text='Для материала — сам текст; для практического задания — что именно нужно сделать.', verbose_name='Текст / инструкция (markdown)')),
                ('youtube_id', models.CharField(blank=True, help_text='Только для видео: ID из ссылки youtube.com/watch?v=XXXX', max_length=32, verbose_name='YouTube ID')),
                ('url', models.URLField(blank=True, help_text='Только для «Ссылка / файл»', verbose_name='Ссылка')),
                ('is_required', models.BooleanField(default=True, help_text='Пока обязательные шаги не выполнены, тест модуля закрыт.', verbose_name='Обязательный')),
                ('requires_note', models.BooleanField(default=False, help_text='Только для практического задания: без короткой заметки ученика отметить шаг нельзя.', verbose_name='Нужна заметка')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (узб.)')),
                ('body_uz', models.TextField(blank=True, verbose_name='Текст (узб., markdown)')),
                ('youtube_id_uz', models.CharField(blank=True, help_text='Если пусто — покажем русское видео', max_length=32, verbose_name='YouTube ID (узб.)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Шаг обучения',
                'verbose_name_plural': 'Шаги обучения',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('note', models.TextField(blank=True, verbose_name='Заметка ученика')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда выполнен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='onboarding.modulestep', verbose_name='Шаг')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='accounts.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
                'unique_together': {('student', 'step')},
            },
        ),
    ]
