# Generated by Django 6.1.1 on 2026-09-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_move_content_to_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='text_content_uz',
        ),
        migrations.RemoveField(
            model_name='module',
            name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='youtube_id_uz',
        ),
    ]
