# Generated by Django 6.1.1 on 2026-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_remove_legacy_module_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Оставь 0 — модуль встанет следом за последним.', unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='modulequestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='modulestep',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
